### ISSUE TITLE
[Question] How was the application deployed?

### ISSUE THREAD

**Issue by longnd** [21jake/nimble-scraper#42]
Issue
--
Since the application is deployed at http://skrape.site, but there is no CI/CD workflow in the codebase, I'm unsure how did you deploy the application and where it is being hosted now (DigitalOcean, Heroku, AWS, ...)?

**Comment by 21jake** [comment]
It's currently being hosted on DigitalOcean, but I'm thinking of moving it back to my personal server tonight. I wish that I hosted it on a server in Vietnam, since the proxy servers are also in Vietnam, thus cut down the network distance to Google's servers

It's built with Docker and deployed with Git and Docker Compose. Anyone can run it on any Linux server by cloning the repository and run one command at the root directory:

`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build`

There's no CI/CD workflow in the codebase because there's no CI/CD. That would be an overkill for this project

**Comment by longnd** [comment]
Thank you for the insights.
